### ISSUE TITLE
wrapClosure problem

### ISSUE THREAD

**Issue by ghost** [tarruda/grunt-traceur-build#1]
https://github.com/tarruda/grunt-traceur-build/blob/master/tasks/traceur_build.js#L47 Need ) instead (). It throws error in chrome 31.0.1650.57

**Comment by tarruda** [comment]
I'm sorry but I'm no longer maintaining this. I think [powerbuild](https://github.com/tarruda/powerbuild) can be as a drop-in replacement for this task
